### ISSUE TITLE
Testing fails

### ISSUE THREAD

**Issue by pyromaniac** [lovely-io/lovely.io-stl#67]
``` bash
guard-mac:~ pyromaniac$ echo $NODE_PATH
/usr/local/share/npm/lib/node_modules:
guard-mac:~ pyromaniac$ lovely test

fs.js:500
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'test'
    at Object.fs.readdirSync (fs.js:500:18)
    at read_dir (/usr/local/share/npm/lib/node_modules/lovely/cli/commands/test.coffee:20:8)
    at Object.exports.init (/usr/local/share/npm/lib/node_modules/lovely/cli/commands/test.coffee:43:5)
    at Object.exports.init (/usr/local/share/npm/lib/node_modules/lovely/cli/commands.coffee:79:32)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/lovely/bin/lovely:4:28)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
```

**Comment by kaievns** [comment]
sup, man. oh, you're just in time with this one, I've recorded the 'how to participate' special for the lovelyio show :)

as you can see it says to you `no such file or directory 'test'`

basically your problem is that youre in a wrong directory. you need to `cd` into some package root folder say stl/dom and run it there. `lovely test` is for testing packages

Also get the latest version of `lovely` and the git rep, i pushed a bunch of updates and fixes yesterday

**Comment by pyromaniac** [comment]
I`ve just install loveli cli at the morning, so yesterday updates shoud be here. Or not? Is SDN updated continuously or on demand?

**Comment by kaievns** [comment]
Yah, it should be there.

CDN. It gets updated automatically once a new version of a package is released, so everything that's on the lovely.io server is immediately available on the CDN

**Comment by pyromaniac** [comment]
And the new version release event is a git tagging, am I right?

**Comment by kaievns** [comment]
Nope, new releases are created with the 'lovely publish' calls, much like ruby gems or npm

**Comment by pyromaniac** [comment]
Gotcha

**Comment by kaievns** [comment]
special delivery! :)

http://lovely.io/show/how-to-participate

**Comment by pyromaniac** [comment]
Command line tools also
